source 'http://rubygems.org'

gem 'rails', '3.2.11'

gem 'bootstrap-sass', '2.1'

gem 'sqlite3'
gem 'mongo_mapper', :git => 'git://github.com/jnunemaker/mongomapper.git', :ref => '4d35c6704a9'
gem 'bson_ext', '1.8.3'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '3.2.5'
  gem 'coffee-rails', '3.2.2'

  gem 'uglifier', '1.2.3'
end

gem 'jquery-rails', '2.0.2'

group :test, :development do
  gem 'rspec-rails', '~> 2.0'
end
